name: Java Build and Synopsys Detect

on:
  push:
    branches:
      - '*'

jobs:
  build-and-detect:
    runs-on: ubuntu-latest-arm64

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Adjust this to your project's Java version
        distribution: 'temurin'  # Uses the Eclipse Temurin distribution
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean package

    - name: Run Synopsys Detect
      run: |
        bash <(curl -s -L https://detect.synopsys.com/detect9.sh)
      env:
        # Add any necessary environment variables for Synopsys Detect
        DETECT_PROJECT_NAME: ${{ github.repository }}
        DETECT_PROJECT_VERSION_NAME: ${{ github.sha }}
        # You might want to add specific Maven-related Detect properties here
        # DETECT_MAVEN_BUILD_COMMAND: 'mvn clean package'
